// 静态字典数据
// demo code
const selectStaticCode: Record<string, any> = {
	carrier: [
		'FedEx',
		'UPS',
		'HZY',
		'AMZN',
		'MDWC',
		'DHL',
		'LSO',
		'USPS',
		'UNIS',
		'mntest0103',
		'carrier007',
		'kiyaCarrier',
		'FGPK',
		'DHL Express',
		'Endicia',
		'SPOT FREIGHT INC',
		'PBD',
		'linls',
		'FCUP',
		'TFRC',
		'MCarry',
		'ShipS',
		'DHLE',
		'PASS',
		'ENDI',
		'Shippo',
		'OnTrac',
		'TEST',
		'Fedex',
		'FDEG',
		'FEDG',
		'UPSP',
		'DHL EXPRESS',
		'PLT',
		'Stripe',
		'ShipL5',
	],
	category: ['WEB', 'ANDROID', 'API', 'ALL', 'MOBILE'],
	carrierServiceCode: ['UPS', 'FEDEX', 'USPS', 'DHL', 'FCUP'],
	carrierProviders: ['UPS', 'FEDEX', 'USPS', 'DHL', 'FCUP'],
	status: ['ACTIVE', 'PENDING', 'INACTIVE'],
	accountType: ['3PL', 'STANDARD'],
	edition: ['Lite', 'Pro'],
	markupType: {
		Promotion: 'Promotion',
		'Individual Account': 'ShipperAccount',
		Carrier: 'Carrier',
	},
	state: {
		AL: 'Alabama',
		AK: 'Alaska',
		AZ: 'Arizona',
		AR: 'Arkansas',
		CA: 'California',
		CO: 'Colorado',
		CT: 'Connecticut',
		DE: 'Delaware',
		FL: 'Florida',
		GA: 'Georgia',
		HI: 'Hawaii',
		ID: 'Idaho',
		IL: 'Illinois',
		IN: 'Indiana',
		IA: 'Iowa',
		KS: 'Kansas',
		KY: 'Kentucky',
		LA: 'Louisiana',
		ME: 'Maine',
		MD: 'Maryland',
		MA: 'Massachusetts',
		MI: 'Michigan',
		MN: 'Minnesota',
		MS: 'Mississippi',
		MO: 'Missouri',
		MT: 'Montana',
		NE: 'Nebraska',
		NV: 'Nevada',
		NH: 'New Hampshire',
		NJ: 'New Jersey',
		NM: 'New Mexico',
		NY: 'New York',
		NC: 'North Carolina',
		ND: 'North Dakota',
		OH: 'Ohio',
		OK: 'Oklahoma',
		OR: 'Oregon',
		PA: 'Pennsylvania',
		RI: 'Rhode Island',
		SC: 'South Carolina',
		SD: 'South Dakota',
		TN: 'Tennessee',
		TX: 'Texas',
		UT: 'Utah',
		VT: 'Vermont',
		VA: 'Virginia',
		WA: 'Washington',
		WV: 'West Virginia',
		WI: 'Wisconsin',
		WY: 'Wyoming',
	},
	defaultWeightUnit: ['kg', 'lb'],
	defaultDimensionUnit: ['cm', 'inch'],
};

export default selectStaticCode;
