/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors');
const tailwind_classes = require('./src/styles/design-system/tailwind-base.json');

// 这是Tailwind CSS的配置文件。它定义了项目的自定义设置和扩展。

export default {
	// 指定Tailwind应该在哪些文件中查找类名
	content: [
		'./public/index.html',
		'./src/**/*.{js,ts,vue}',
	],
	theme: {
		extend: {
			// 扩展颜色配置，包括自定义颜色和透明色
			colors: {
				...tailwind_classes,
				transparent: 'transparent',
				current: 'currentColor',
				primary: {
					DEFAULT: 'var(--bg-primary)',
					hover: 'var(--bg-primary-hover)',
					foreground: 'var(--text-primary)',
					border: 'var(--border-primary)',
				},
				secondary: {
					DEFAULT: 'var(--bg-secondary)',
					hover: 'var(--bg-secondary-hover)',
					foreground: 'var(--text-secondary)',
					border: 'var(--border-secondary)',
				},
				tertiary: {
					DEFAULT: 'var(--bg-tertiary)',
					hover: 'var(--bg-tertiary-hover)',
					foreground: 'var(--text-tertiary)',
					border: 'var(--border-tertiary)',
				},
				filled: 'var(--bg-filled)',
				outlined: 'var(--bg-outlined)',
				disabled: {
					DEFAULT: 'var(--bg-disabled)',
					foreground: 'var(--text-disabled)',
					border: 'var(--border-disabled)',
				},
				positive: {
					DEFAULT: 'var(--bg-positive-primary)',
					hover: 'var(--bg-positive-primary-hover)',
					secondary: 'var(--bg-positive-secondary)',
					'secondary-hover': 'var(--bg-positive-secondary-hover)',
					tertiary: 'var(--bg-positive-tertiary)',
					'tertiary-hover': 'var(--bg-positive-tertiary-hover)',
					foreground: 'var(--text-positive)',
					border: {
						DEFAULT: 'var(--border-positive-primary)',
						secondary: 'var(--border-positive-secondary)',
						tertiary: 'var(--border-positive-tertiary)',
					},
				},
				warning: {
					DEFAULT: 'var(--bg-warning-primary)',
					hover: 'var(--bg-warning-primary-hover)',
					secondary: 'var(--bg-warning-secondary)',
					'secondary-hover': 'var(--bg-warning-secondary-hover)',
					tertiary: 'var(--bg-warning-tertiary)',
					'tertiary-hover': 'var(--bg-warning-tertiary-hover)',
					foreground: 'var(--text-warning)',
					border: {
						DEFAULT: 'var(--border-warning-primary)',
						secondary: 'var(--border-warning-secondary)',
						tertiary: 'var(--border-warning-tertiary)',
					},
				},
				danger: {
					DEFAULT: 'var(--bg-danger-primary)',
					hover: 'var(--bg-danger-primary-hover)',
					secondary: 'var(--bg-danger-secondary)',
					'secondary-hover': 'var(--bg-danger-secondary-hover)',
					tertiary: 'var(--bg-danger-tertiary)',
					'tertiary-hover': 'var(--bg-danger-tertiary-hover)',
					foreground: 'var(--text-danger)',
					border: {
						DEFAULT: 'var(--border-danger-primary)',
						secondary: 'var(--border-danger-secondary)',
						tertiary: 'var(--border-danger-tertiary)',
					},
				},
				brand: {
					DEFAULT: 'var(--bg-brand-primary)',
					hover: 'var(--bg-brand-primary-hover)',
					secondary: 'var(--bg-brand-secondary)',
					'secondary-hover': 'var(--bg-brand-secondary-hover)',
					tertiary: 'var(--bg-brand-tertiary)',
					'tertiary-hover': 'var(--bg-brand-tertiary-hover)',
					foreground: 'var(--text-brand)',
					border: {
						DEFAULT: 'var(--border-brand-primary)',
						secondary: 'var(--border-brand-secondary)',
						tertiary: 'var(--border-brand-tertiary)',
					},
				},
				on: {
					positive: {
						primary: 'var(--text-on-positive-primary)',
						secondary: 'var(--text-on-positive-secondary)',
						tertiary: 'var(--text-on-positive-tertiary)',
					},
					warning: {
						primary: 'var(--text-on-warning-primary)',
						secondary: 'var(--text-on-warning-secondary)',
						tertiary: 'var(--text-on-warning-tertiary)',
					},
					danger: {
						DEFAULT: 'var(--text-on-danger-primary)',
						secondary: 'var(--text-on-danger-secondary)',
						tertiary: 'var(--text-on-danger-tertiary)',
					},
					brand: 'var(--text-on-brand)',
				}
			},
			// 设置默认字体
			fontFamily: {
				sans: ['HelveticaNow']
			},
		},
	},
	// 启用暗黑模式
	darkMode: "class",
	plugins: [
		// 自定义插件，用于添加基础样式和组件
		function ({ addBase, addComponents }) {
			// 为Element UI的按钮添加基础样式
			addBase({
				".el-button": {
					"background-color": "var(--el-button-bg-color,var(--el-color-white))"
				}
			});
			// 添加大量CSS变量到:root，这些变量对应于tailwind_classes中定义的颜色
			addBase({
				':root': {
					// 这里定义了大量的CSS变量，每个变量对应tailwind_classes中的一个颜色值
					// 例如："--black-50": tailwind_classes["black"]["50"],
					// 这允许在整个项目中使用这些颜色变量
					"--black-50": tailwind_classes["black"]["50"],
					"--black-100": tailwind_classes["black"]["100"],
					"--black-200": tailwind_classes["black"]["200"],
					"--black-300": tailwind_classes["black"]["300"],
					"--black-400": tailwind_classes["black"]["400"],
					"--black-500": tailwind_classes["black"]["500"],
					"--black-600": tailwind_classes["black"]["600"],
					"--black-700": tailwind_classes["black"]["700"],
					"--black-800": tailwind_classes["black"]["800"],
					"--black-900": tailwind_classes["black"]["900"],
					"--black-950": tailwind_classes["black"]["950"],
					"--black-1000": tailwind_classes["black"]["1000"],
					"--white-50": tailwind_classes["white"]["50"],
					"--white-100": tailwind_classes["white"]["100"],
					"--white-200": tailwind_classes["white"]["200"],
					"--white-300": tailwind_classes["white"]["300"],
					"--white-400": tailwind_classes["white"]["400"],
					"--white-500": tailwind_classes["white"]["500"],
					"--white-600": tailwind_classes["white"]["600"],
					"--white-700": tailwind_classes["white"]["700"],
					"--white-800": tailwind_classes["white"]["800"],
					"--white-900": tailwind_classes["white"]["900"],
					"--white-950": tailwind_classes["white"]["950"],
					"--white-1000": tailwind_classes["white"]["1000"],
					"--slate-50": tailwind_classes["slate"]["50"],
					"--slate-100": tailwind_classes["slate"]["100"],
					"--slate-200": tailwind_classes["slate"]["200"],
					"--slate-300": tailwind_classes["slate"]["300"],
					"--slate-400": tailwind_classes["slate"]["400"],
					"--slate-500": tailwind_classes["slate"]["500"],
					"--slate-600": tailwind_classes["slate"]["600"],
					"--slate-700": tailwind_classes["slate"]["700"],
					"--slate-800": tailwind_classes["slate"]["800"],
					"--slate-900": tailwind_classes["slate"]["900"],
					"--slate-950": tailwind_classes["slate"]["950"],
					"--slate-1000": tailwind_classes["slate"]["1000"],
					"--gray-50": tailwind_classes["gray"]["50"],
					"--gray-100": tailwind_classes["gray"]["100"],
					"--gray-200": tailwind_classes["gray"]["200"],
					"--gray-300": tailwind_classes["gray"]["300"],
					"--gray-400": tailwind_classes["gray"]["400"],
					"--gray-500": tailwind_classes["gray"]["500"],
					"--gray-600": tailwind_classes["gray"]["600"],
					"--gray-700": tailwind_classes["gray"]["700"],
					"--gray-800": tailwind_classes["gray"]["800"],
					"--gray-900": tailwind_classes["gray"]["900"],
					"--gray-950": tailwind_classes["gray"]["950"],
					"--zinc-50": tailwind_classes["zinc"]["50"],
					"--zinc-100": tailwind_classes["zinc"]["100"],
					"--zinc-200": tailwind_classes["zinc"]["200"],
					"--zinc-300": tailwind_classes["zinc"]["300"],
					"--zinc-400": tailwind_classes["zinc"]["400"],
					"--zinc-500": tailwind_classes["zinc"]["500"],
					"--zinc-600": tailwind_classes["zinc"]["600"],
					"--zinc-700": tailwind_classes["zinc"]["700"],
					"--zinc-800": tailwind_classes["zinc"]["800"],
					"--zinc-900": tailwind_classes["zinc"]["900"],
					"--zinc-950": tailwind_classes["zinc"]["950"],
					"--neutral-50": tailwind_classes["neutral"]["50"],
					"--neutral-100": tailwind_classes["neutral"]["100"],
					"--neutral-200": tailwind_classes["neutral"]["200"],
					"--neutral-300": tailwind_classes["neutral"]["300"],
					"--neutral-400": tailwind_classes["neutral"]["400"],
					"--neutral-500": tailwind_classes["neutral"]["500"],
					"--neutral-600": tailwind_classes["neutral"]["600"],
					"--neutral-700": tailwind_classes["neutral"]["700"],
					"--neutral-800": tailwind_classes["neutral"]["800"],
					"--neutral-900": tailwind_classes["neutral"]["900"],
					"--neutral-950": tailwind_classes["neutral"]["950"],
					"--stone-50": tailwind_classes["stone"]["50"],
					"--stone-100": tailwind_classes["stone"]["100"],
					"--stone-200": tailwind_classes["stone"]["200"],
					"--stone-300": tailwind_classes["stone"]["300"],
					"--stone-400": tailwind_classes["stone"]["400"],
					"--stone-500": tailwind_classes["stone"]["500"],
					"--stone-600": tailwind_classes["stone"]["600"],
					"--stone-700": tailwind_classes["stone"]["700"],
					"--stone-800": tailwind_classes["stone"]["800"],
					"--stone-900": tailwind_classes["stone"]["900"],
					"--stone-950": tailwind_classes["stone"]["950"],
					"--red-50": tailwind_classes["red"]["50"],
					"--red-100": tailwind_classes["red"]["100"],
					"--red-200": tailwind_classes["red"]["200"],
					"--red-300": tailwind_classes["red"]["300"],
					"--red-400": tailwind_classes["red"]["400"],
					"--red-500": tailwind_classes["red"]["500"],
					"--red-600": tailwind_classes["red"]["600"],
					"--red-700": tailwind_classes["red"]["700"],
					"--red-800": tailwind_classes["red"]["800"],
					"--red-900": tailwind_classes["red"]["900"],
					"--red-950": tailwind_classes["red"]["950"],
					"--orange-50": tailwind_classes["orange"]["50"],
					"--orange-100": tailwind_classes["orange"]["100"],
					"--orange-200": tailwind_classes["orange"]["200"],
					"--orange-300": tailwind_classes["orange"]["300"],
					"--orange-400": tailwind_classes["orange"]["400"],
					"--orange-500": tailwind_classes["orange"]["500"],
					"--orange-600": tailwind_classes["orange"]["600"],
					"--orange-700": tailwind_classes["orange"]["700"],
					"--orange-800": tailwind_classes["orange"]["800"],
					"--orange-900": tailwind_classes["orange"]["900"],
					"--orange-950": tailwind_classes["orange"]["950"],
					"--amber-50": tailwind_classes["amber"]["50"],
					"--amber-100": tailwind_classes["amber"]["100"],
					"--amber-200": tailwind_classes["amber"]["200"],
					"--amber-300": tailwind_classes["amber"]["300"],
					"--amber-400": tailwind_classes["amber"]["400"],
					"--amber-500": tailwind_classes["amber"]["500"],
					"--amber-600": tailwind_classes["amber"]["600"],
					"--amber-700": tailwind_classes["amber"]["700"],
					"--amber-800": tailwind_classes["amber"]["800"],
					"--amber-900": tailwind_classes["amber"]["900"],
					"--amber-950": tailwind_classes["amber"]["950"],
					"--yellow-50": tailwind_classes["yellow"]["50"],
					"--yellow-100": tailwind_classes["yellow"]["100"],
					"--yellow-200": tailwind_classes["yellow"]["200"],
					"--yellow-300": tailwind_classes["yellow"]["300"],
					"--yellow-400": tailwind_classes["yellow"]["400"],
					"--yellow-500": tailwind_classes["yellow"]["500"],
					"--yellow-600": tailwind_classes["yellow"]["600"],
					"--yellow-700": tailwind_classes["yellow"]["700"],
					"--yellow-800": tailwind_classes["yellow"]["800"],
					"--yellow-900": tailwind_classes["yellow"]["900"],
					"--yellow-950": tailwind_classes["yellow"]["950"],
					"--lime-50": tailwind_classes["lime"]["50"],
					"--lime-100": tailwind_classes["lime"]["100"],
					"--lime-200": tailwind_classes["lime"]["200"],
					"--lime-300": tailwind_classes["lime"]["300"],
					"--lime-400": tailwind_classes["lime"]["400"],
					"--lime-500": tailwind_classes["lime"]["500"],
					"--lime-600": tailwind_classes["lime"]["600"],
					"--lime-700": tailwind_classes["lime"]["700"],
					"--lime-800": tailwind_classes["lime"]["800"],
					"--lime-900": tailwind_classes["lime"]["900"],
					"--lime-950": tailwind_classes["lime"]["950"],
					"--green-50": tailwind_classes["green"]["50"],
					"--green-100": tailwind_classes["green"]["100"],
					"--green-200": tailwind_classes["green"]["200"],
					"--green-300": tailwind_classes["green"]["300"],
					"--green-400": tailwind_classes["green"]["400"],
					"--green-500": tailwind_classes["green"]["500"],
					"--green-600": tailwind_classes["green"]["600"],
					"--green-700": tailwind_classes["green"]["700"],
					"--green-800": tailwind_classes["green"]["800"],
					"--green-900": tailwind_classes["green"]["900"],
					"--green-950": tailwind_classes["green"]["950"],
					"--emerald-50": tailwind_classes["emerald"]["50"],
					"--emerald-100": tailwind_classes["emerald"]["100"],
					"--emerald-200": tailwind_classes["emerald"]["200"],
					"--emerald-300": tailwind_classes["emerald"]["300"],
					"--emerald-400": tailwind_classes["emerald"]["400"],
					"--emerald-500": tailwind_classes["emerald"]["500"],
					"--emerald-600": tailwind_classes["emerald"]["600"],
					"--emerald-700": tailwind_classes["emerald"]["700"],
					"--emerald-800": tailwind_classes["emerald"]["800"],
					"--emerald-900": tailwind_classes["emerald"]["900"],
					"--emerald-950": tailwind_classes["emerald"]["950"],
					"--teal-50": tailwind_classes["teal"]["50"],
					"--teal-100": tailwind_classes["teal"]["100"],
					"--teal-200": tailwind_classes["teal"]["200"],
					"--teal-300": tailwind_classes["teal"]["300"],
					"--teal-400": tailwind_classes["teal"]["400"],
					"--teal-500": tailwind_classes["teal"]["500"],
					"--teal-600": tailwind_classes["teal"]["600"],
					"--teal-700": tailwind_classes["teal"]["700"],
					"--teal-800": tailwind_classes["teal"]["800"],
					"--teal-900": tailwind_classes["teal"]["900"],
					"--teal-950": tailwind_classes["teal"]["950"],
					"--cyan-50": tailwind_classes["cyan"]["50"],
					"--cyan-100": tailwind_classes["cyan"]["100"],
					"--cyan-200": tailwind_classes["cyan"]["200"],
					"--cyan-300": tailwind_classes["cyan"]["300"],
					"--cyan-400": tailwind_classes["cyan"]["400"],
					"--cyan-500": tailwind_classes["cyan"]["500"],
					"--cyan-600": tailwind_classes["cyan"]["600"],
					"--cyan-700": tailwind_classes["cyan"]["700"],
					"--cyan-800": tailwind_classes["cyan"]["800"],
					"--cyan-900": tailwind_classes["cyan"]["900"],
					"--cyan-950": tailwind_classes["cyan"]["950"],
					"--sky-50": tailwind_classes["sky"]["50"],
					"--sky-100": tailwind_classes["sky"]["100"],
					"--sky-200": tailwind_classes["sky"]["200"],
					"--sky-300": tailwind_classes["sky"]["300"],
					"--sky-400": tailwind_classes["sky"]["400"],
					"--sky-500": tailwind_classes["sky"]["500"],
					"--sky-600": tailwind_classes["sky"]["600"],
					"--sky-700": tailwind_classes["sky"]["700"],
					"--sky-800": tailwind_classes["sky"]["800"],
					"--sky-900": tailwind_classes["sky"]["900"],
					"--sky-950": tailwind_classes["sky"]["950"],
					"--blue-50": tailwind_classes["blue"]["50"],
					"--blue-100": tailwind_classes["blue"]["100"],
					"--blue-200": tailwind_classes["blue"]["200"],
					"--blue-300": tailwind_classes["blue"]["300"],
					"--blue-400": tailwind_classes["blue"]["400"],
					"--blue-500": tailwind_classes["blue"]["500"],
					"--blue-600": tailwind_classes["blue"]["600"],
					"--blue-700": tailwind_classes["blue"]["700"],
					"--blue-800": tailwind_classes["blue"]["800"],
					"--blue-900": tailwind_classes["blue"]["900"],
					"--blue-950": tailwind_classes["blue"]["950"],
					"--indigo-50": tailwind_classes["indigo"]["50"],
					"--indigo-100": tailwind_classes["indigo"]["100"],
					"--indigo-200": tailwind_classes["indigo"]["200"],
					"--indigo-300": tailwind_classes["indigo"]["300"],
					"--indigo-400": tailwind_classes["indigo"]["400"],
					"--indigo-500": tailwind_classes["indigo"]["500"],
					"--indigo-600": tailwind_classes["indigo"]["600"],
					"--indigo-700": tailwind_classes["indigo"]["700"],
					"--indigo-800": tailwind_classes["indigo"]["800"],
					"--indigo-900": tailwind_classes["indigo"]["900"],
					"--indigo-950": tailwind_classes["indigo"]["950"],
					"--violet-50": tailwind_classes["violet"]["50"],
					"--violet-100": tailwind_classes["violet"]["100"],
					"--violet-200": tailwind_classes["violet"]["200"],
					"--violet-300": tailwind_classes["violet"]["300"],
					"--violet-400": tailwind_classes["violet"]["400"],
					"--violet-500": tailwind_classes["violet"]["500"],
					"--violet-600": tailwind_classes["violet"]["600"],
					"--violet-700": tailwind_classes["violet"]["700"],
					"--violet-800": tailwind_classes["violet"]["800"],
					"--violet-900": tailwind_classes["violet"]["900"],
					"--violet-950": tailwind_classes["violet"]["950"],
					"--purple-50": tailwind_classes["purple"]["50"],
					"--purple-100": tailwind_classes["purple"]["100"],
					"--purple-200": tailwind_classes["purple"]["200"],
					"--purple-300": tailwind_classes["purple"]["300"],
					"--purple-400": tailwind_classes["purple"]["400"],
					"--purple-500": tailwind_classes["purple"]["500"],
					"--purple-600": tailwind_classes["purple"]["600"],
					"--purple-700": tailwind_classes["purple"]["700"],
					"--purple-800": tailwind_classes["purple"]["800"],
					"--purple-900": tailwind_classes["purple"]["900"],
					"--purple-950": tailwind_classes["purple"]["950"],
					"--fuchsia-50": tailwind_classes["fuchsia"]["50"],
					"--fuchsia-100": tailwind_classes["fuchsia"]["100"],
					"--fuchsia-200": tailwind_classes["fuchsia"]["200"],
					"--fuchsia-300": tailwind_classes["fuchsia"]["300"],
					"--fuchsia-400": tailwind_classes["fuchsia"]["400"],
					"--fuchsia-500": tailwind_classes["fuchsia"]["500"],
					"--fuchsia-600": tailwind_classes["fuchsia"]["600"],
					"--fuchsia-700": tailwind_classes["fuchsia"]["700"],
					"--fuchsia-800": tailwind_classes["fuchsia"]["800"],
					"--fuchsia-900": tailwind_classes["fuchsia"]["900"],
					"--fuchsia-950": tailwind_classes["fuchsia"]["950"],
					"--pink-50": tailwind_classes["pink"]["50"],
					"--pink-100": tailwind_classes["pink"]["100"],
					"--pink-200": tailwind_classes["pink"]["200"],
					"--pink-300": tailwind_classes["pink"]["300"],
					"--pink-400": tailwind_classes["pink"]["400"],
					"--pink-500": tailwind_classes["pink"]["500"],
					"--pink-600": tailwind_classes["pink"]["600"],
					"--pink-700": tailwind_classes["pink"]["700"],
					"--pink-800": tailwind_classes["pink"]["800"],
					"--pink-900": tailwind_classes["pink"]["900"],
					"--pink-950": tailwind_classes["pink"]["950"],
					"--rose-50": tailwind_classes["rose"]["50"],
					"--rose-100": tailwind_classes["rose"]["100"],
					"--rose-200": tailwind_classes["rose"]["200"],
					"--rose-300": tailwind_classes["rose"]["300"],
					"--rose-400": tailwind_classes["rose"]["400"],
					"--rose-500": tailwind_classes["rose"]["500"],
					"--rose-600": tailwind_classes["rose"]["600"],
					"--rose-700": tailwind_classes["rose"]["700"],
					"--rose-800": tailwind_classes["rose"]["800"],
					"--rose-900": tailwind_classes["rose"]["900"],
					"--rose-950": tailwind_classes["rose"]["950"],
				},
			});
		},
	],
};
